const ADJECTIVES = [
  "Swift",
  "Wise",
  "Bold",
  "Fierce",
  "Noble",
  "Ancient",
  "Golden",
  "Silver",
  "Divine",
  "Mighty",
  "Cunning",
  "Valiant",
  "Radiant",
  "Shadow",
  "Storm",
  "Iron",
  "Eternal",
  "Silent",
  "Blazing",
  "Frost",
];

const GREEK_FIGURES = [
  "Zeus",
  "Hera",
  "Poseidon",
  "Athena",
  "Apollo",
  "Artemis",
  "Hermes",
  "Dionysus",
  "Hades",
  "Persephone",
  "Demeter",
  "Ares",
  "Aphrodite",
  "Hephaestus",
  "Hestia",
  "Icarus",
  "Orpheus",
  "Achilles",
  "Odysseus",
  "Perseus",
  "Theseus",
  "Heracles",
  "Medusa",
  "Pandora",
  "Prometheus",
  "Atlas",
  "Cronus",
  "Rhea",
  "Helios",
  "Selene",
  "Eros",
  "Nike",
  "Nemesis",
  "Morpheus",
  "Hypnos",
];

const COLORS = [
  "#e57373",
  "#f06292",
  "#ba68c8",
  "#9575cd",
  "#7986cb",
  "#64b5f6",
  "#4fc3f7",
  "#4dd0e1",
  "#4db6ac",
  "#81c784",
  "#aed581",
  "#dce775",
  "#fff176",
  "#ffd54f",
  "#ffb74d",
  "#ff8a65",
  "#a1887f",
  "#90a4ae",
];

export function generateIdentity() {
  const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)];
  const name = GREEK_FIGURES[Math.floor(Math.random() * GREEK_FIGURES.length)];
  const color = COLORS[Math.floor(Math.random() * COLORS.length)];
  return { name: `${adj} ${name}`, color };
}
